/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary": "#234645",
        "tertiary-fixed-dim": "#ec9796",
        "inverse-surface": "#f9f9ff",
        "surface-container": "#161a21",
        "secondary-dim": "#91a384",
        "on-surface": "#e0e5f5",
        "on-error-container": "#ff9993",
        "outline": "#6f7583",
        "on-background": "#e0e5f5",
        "surface-tint": "#a9cecc",
        "on-tertiary-container": "#602627",
        "primary-fixed-dim": "#b6dcda",
        "on-tertiary": "#6c2f30",
        "tertiary-container": "#fba4a3",
        "tertiary-fixed": "#fba4a3",
        "on-secondary-fixed-variant": "#4f6045",
        "primary-fixed": "#c4eae8",
        "on-primary-container": "#b2d7d6",
        "surface": "#0c0e12",
        "on-tertiary-fixed-variant": "#6b2e2f",
        "error-container": "#7f2927",
        "inverse-on-surface": "#53555a",
        "surface-container-highest": "#202631",
        "on-secondary": "#15240e",
        "secondary": "#91a384",
        "primary-dim": "#9bc0be",
        "tertiary-dim": "#ec9796",
        "on-error": "#490106",
        "error-dim": "#bb5551",
        "tertiary": "#ffb7b6",
        "on-surface-variant": "#a5abba",
        "on-primary-fixed-variant": "#3f6161",
        "primary-container": "#2a4c4c",
        "surface-container-lowest": "#000000",
        "primary": "#a9cecc",
        "surface-variant": "#202631",
        "on-primary-fixed": "#224544",
        "background": "#0c0e12",
        "secondary-container": "#304027",
        "on-tertiary-fixed": "#441013",
        "on-secondary-container": "#b2c5a4",
        "surface-container-low": "#111319",
        "surface-dim": "#0c0e12",
        "surface-bright": "#252c3a",
        "on-secondary-fixed": "#34442b",
        "surface-container-high": "#1b2029",
        "secondary-fixed": "#d5e9c6",
        "secondary-fixed-dim": "#c7dab8",
        "outline-variant": "#424854",
        "inverse-primary": "#426564",
        "error": "#ee7d77"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "headline": ["Inter"],
        "body": ["Inter"],
        "label": ["Inter"],
        "mono": ["JetBrains Mono"]
      }
    },
  },
  plugins: [],
}
